FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /src

COPY ["backend.csproj", "./"]
RUN dotnet restore "backend.csproj"

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

EXPOSE 5001

ENTRYPOINT ["dotnet", "watch", "run", "--project", "backend.csproj", "--urls", "http://+:5001"]
